# Generated by Django 6.0.7 on 2026-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_add_username_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Libera o painel gerencial (dashboards e alteracao de status).', verbose_name='Acesso administrativo'),
        ),
    ]
